### ISSUE TITLE
Figure out how to work with bool ctls

### ISSUE THREAD

**Issue by sfackler** [sfackler/jemalloc-ctl#1]
The FFI story around C bools is a bit undecided. In the the System V x86_64 and ARM ABIs, bool is passed as a u8, but I'm not sure if that's universal.

@alexcrichton do you know what the deal is here?

**Comment by alexcrichton** [comment]
Nah I'm not sure what's the best way to do this. I'd probably just work with u8 and then fix bugs as they arise.
